### ISSUE TITLE
Add support for multikey indexes

### ISSUE THREAD

**Issue by bfink13** [bwaldvogel/mongo-java-server#69]
[Multikey indexes](https://docs.mongodb.com/manual/core/index-multikey/) don't seem to be supported currently.

I took a stab at the implementation, but I ended up going down a rabbit hole of all the different edge cases that need to be supported. Any ideas on where to start with this?

**Comment by bwaldvogel** [comment]
Could you provide simple test cases?

**Comment by bfink13** [comment]
Sorry it has taken me so long to get back to this issue.

Here's an example based off the [multikey documentation](https://docs.mongodb.com/manual/core/index-multikey/#index-arrays-with-embedded-documents):

**Mongo shell**
```
rs0:PRIMARY> db.test.createIndex({ 'item': 1, 'stock.size': 1 }, {unique: true});
{
	"createdCollectionAutomatically" : false,
	"numIndexesBefore" : 1,
	"numIndexesAfter" : 2,
	"ok" : 1
}
rs0:PRIMARY> db.test.insert({_id:1, item:'abc', stock:[{size:'S', color:'red'}]});
WriteResult({ "nInserted" : 1 })
rs0:PRIMARY> db.test.insert({_id:2, item:'abc', stock:[{size:'L', color:'black'}]});
WriteResult({ "nInserted" : 1 })
rs0:PRIMARY> db.test.find()
{ "_id" : 1, "item" : "abc", "stock" : [ { "size" : "S", "color" : "red" } ] }
{ "_id" : 2, "item" : "abc", "stock" : [ { "size" : "L", "color" : "black" } ] }
```
**mongo-java-server MemoryBackend**
```
final MongoServer mongoServer = new MongoServer(new MemoryBackend());
mongoServer.bind();
final MongoClient client = new MongoClient(new ServerAddress(mongoServer.getLocalAddress()));

final MongoCollection collection = client.getDatabase("testdb").getCollection("testcollection");
collection.createIndex(BsonDocument.parse("{ 'item': 1, 'stock.size': 1 }"), new IndexOptions().unique(true));

final Document doc1 = new Document("_id", 1)
        .append("item", "abc")
        .append("stock", Lists.newArrayList(
                new BasicDBObjectBuilder().add("size", "S").add("color", "red").get()
        ));

final Document doc2 = new Document("_id", 2)
        .append("item", "abc")
        .append("stock", Lists.newArrayList(
                new BasicDBObjectBuilder().add("size", "L").add("color", "black").get()
        ));

collection.insertOne(doc1);
collection.insertOne(doc2); // <---------- Fails
```
The last line (`collection.insertOne(doc2)`) fails with `com.mongodb.MongoWriteException: E11000 duplicate key error collection: testdb.testcollection index: item_1_stock.size_1 dup key: { : "abc", : null }`.

I believe to issue lies in how the 'key value' is generated in `Index.java` in `getKeyValue()`. For the above example, the first `collection.insertOne` results in an index key of `[abc, null]`.

**Comment by bwaldvogel** [comment]
With edddc9587d25c9cd1ce78287790338f598de9ef4 (part of version `1.17.1`) compound unique indexes don’t throw an exception anymore. However, they currently don’t find uniqueness violations.

**Comment by bfink13** [comment]
Good deal. Any thoughts on how to best approach uniqueness?

**Comment by bwaldvogel** [comment]
I’ve started the first steps to support unique (compound) multikey indices.

> I believe to issue lies in how the 'key value' is generated in `Index.java` in `getKeyValue()`. For the above example, the first collection.insertOne results in an index key of `[abc, null]`.

Yes, good catch!

[In a first step, I’ve refactored](1645efd2c3daaeb4aeb0d458a0e5b169b4a0a617) `getKeyValue()` to return a `KeyValue` (instead of `List<Object>`). `KeyValue` represents the index key value for a document. It contains a single value for a simple index and multiple values for compound indices.
[In a second step](f0f7f4037f80c9e553ac10e2cad130394874e89d), `getKeyValue()` became `getKeyValues()` and returns `List<KeyValue>` so indices should be ready to support multiple keys per document.

The first two simple use cases work already but there’s some more work to do such as support for index updates.

**Comment by bwaldvogel** [comment]
I’ve continued working on multikey index support in https://github.com/bwaldvogel/mongo-java-server/commit/e6e89dccb13ebabb2e5a5dde42cdbbc5c364f51d and https://github.com/bwaldvogel/mongo-java-server/commit/e28b80f46308365462e9575a5d056d76236fd479.
BTW: It turned out that `List<KeyValue>` must be `Set<KeyValue>`, of course.

@bfink13: Could you run your tests with latest master?

**Comment by bwaldvogel** [comment]
The changes are part of version `1.18.0`.

**Comment by bfink13** [comment]
Sorry I haven't gotten back to you on this - thanks for merging. I'll try to sanity-check my tests in the next day or two.
